---
title: "Data Request"
author: "Keith Lee & Joseph Robbins"
date: "`r Sys.Date()`"
output: pdf_document
---


# Since January of 2020 which, if any, support resources did you need but could not access?

```{r message=FALSE, warning=FALSE, echo=FALSE}


library(qualtRics)
library(Hmisc)
library(tidyverse)
library(gt)
library(gtExtras)


data <- read_survey("qualtrics-data.csv")

today.date <- Sys.Date()

serv_need <- data |> 
  select(resources_non_access) |> 
  arrange(resources_non_access)

table <- as_tibble(unlist(strsplit(serv_need$resources_non_access,",")))

table |> 
  filter(!is.na(value),
         value != "None",
         value != "Other (please specify)") |> 
  group_by(value) |> 
  count() |> 
  ggplot(aes(x = reorder(value,n), y = n, fill=value)) +
  geom_col() + 
  coord_flip() + 
  labs(x = "Resources Needed",
       y = "Number of Respondents") +
  geom_text(aes(label = n,
                hjust = 1.25)) + 
  theme_classic() + 
  theme(legend.position = "none")
  
```

\newpage


# For each of the following topics, select the option that best describes how stressful each are for you currently.


```{r warning = FALSE, message=FALSE, echo=FALSE}

housing_stress <- as.data.frame(table(data$housing_stress)) %>% # create data frame
    mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
    arrange(desc(Percentage))


housing_table <- housing_stress |> 
  mutate(Ordered = fct_relevel(Var1, 
                               c('Very stressful', 
                                 'Somewhat stressful',
                                 'Not stressful',
                                 'Not applicable, do not have to pay for this'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Housing Costs"
  )

housing_table

```


```{r warning = FALSE, message=FALSE, echo=FALSE}

energy_stress <- as.data.frame(table(data$energy_stress)) %>% # create data frame
    mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
    arrange(desc(Percentage))


energy_table <- energy_stress |> 
  mutate(Ordered = fct_relevel(Var1, 
                               c('Very stressful', 
                                 'Somewhat stressful',
                                 'Not stressful',
                                 'Not applicable, do not have to pay for this'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Home Energy Costs"
  )

energy_table

```



```{r warning = FALSE, message=FALSE, echo=FALSE}

food_stress <- as.data.frame(table(data$food_stress)) %>% # create data frame
    mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
    arrange(desc(Percentage))


food_table <- food_stress |> 
  mutate(Ordered = fct_relevel(Var1, 
                               c('Very stressful', 
                                 'Somewhat stressful',
                                 'Not stressful',
                                 'Not applicable, do not have to pay for this'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Food Costs"
  )

food_table

```


```{r warning = FALSE, message=FALSE, echo=FALSE}

trans_stress <- as.data.frame(table(data$trans_stress)) %>% # create data frame
    mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
    arrange(desc(Percentage))


trans_table <- trans_stress |> 
  mutate(Ordered = fct_relevel(Var1, 
                               c('Very stressful', 
                                 'Somewhat stressful',
                                 'Not stressful',
                                 'Not applicable, do not have to pay for this'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Access to Reliable Transportation"
  )

trans_table

```




```{r message=FALSE, warning=FALSE, echo=FALSE, include = FALSE}
happy <- as.data.frame(table(data$happy)) %>% # create data frame
    mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
    arrange(desc(Percentage))



happy_table <- happy |> 
  mutate(Ordered = fct_relevel(Var1, c('Nearly always', 
                                           'Most of the time',
                                           'Some of the time',
                                           'Rarely'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Happy"
  )

happy_table
```


```{r message=FALSE, warning=FALSE, echo=FALSE, include = FALSE}


sad <- as.data.frame(table(data$sad)) %>% # create data frame
  mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
  arrange(desc(Percentage))



sad_table <- sad |> 
  mutate(Ordered = fct_relevel(Var1, c('Nearly always', 
                                       'Most of the time',
                                       'Some of the time',
                                       'Rarely'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Sad"
  )

sad_table
```



```{r message=FALSE, warning=FALSE, echo=FALSE, include = FALSE}
stressed <- as.data.frame(table(data$stressed)) %>% # create data frame
  mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
  arrange(desc(Percentage))



stressed_table <- stressed |> 
  mutate(Ordered = fct_relevel(Var1, c('Nearly always', 
                                       'Most of the time',
                                       'Some of the time',
                                       'Rarely'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Stressed"
  )

stressed_table
```




```{r message=FALSE, warning=FALSE, echo=FALSE, include = FALSE}


angry <- as.data.frame(table(data$angry)) %>% # create data frame
  mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
  arrange(desc(Percentage))



angry_table <- angry |> 
  mutate(Ordered = fct_relevel(Var1, c('Nearly always', 
                                       'Most of the time',
                                       'Some of the time',
                                       'Rarely'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Angry"
  )

angry_table

```

```{r message=FALSE, warning=FALSE, echo=FALSE, include = FALSE}

# frustrated

frustrated <- as.data.frame(table(data$frustrated)) %>% # create data frame
  mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
  arrange(desc(Percentage))



frustrated_table <- frustrated |> 
  mutate(Ordered = fct_relevel(Var1, c('Nearly always', 
                                       'Most of the time',
                                       'Some of the time',
                                       'Rarely'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Frustrated"
  )

frustrated_table

```




```{r message=FALSE, warning=FALSE, echo=FALSE, include = FALSE}

# tired

tired <- as.data.frame(table(data$tired)) %>% # create data frame
  mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
  arrange(desc(Percentage))



tired_table <- tired |> 
  mutate(Ordered = fct_relevel(Var1, c('Nearly always', 
                                       'Most of the time',
                                       'Some of the time',
                                       'Rarely'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Tired"
  )

tired_table

```

```{r message=FALSE, warning=FALSE, echo=FALSE, include = FALSE}

# hopeful

hopeful <- as.data.frame(table(data$hopeful)) %>% # create data frame
  mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
  arrange(desc(Percentage))



hopeful_table <- hopeful |> 
  mutate(Ordered = fct_relevel(Var1, c('Nearly always', 
                                       'Most of the time',
                                       'Some of the time',
                                       'Rarely'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Hopeful"
  )

hopeful_table

```

```{r message=FALSE, warning=FALSE, echo=FALSE, include = FALSE}

# worried

worried <- as.data.frame(table(data$worried)) %>% # create data frame
  mutate(Percentage = round(Freq / sum(Freq) * 100, 2)) %>%
  arrange(desc(Percentage))



worried_table <- worried |> 
  mutate(Ordered = fct_relevel(Var1, c('Nearly always', 
                                       'Most of the time',
                                       'Some of the time',
                                       'Rarely'))) |> 
  arrange(Ordered) |> 
  gt() |> 
  cols_label(
    Var1 = "Response",
    Freq = "Count") %>%
  cols_align(
    align = "left",
    columns = Var1
  ) |> 
  cols_hide(Ordered) |> 
  tab_header(
    title = "Worried"
  )

worried_table
```
